### ISSUE TITLE
exec format error on amd64 box

### ISSUE THREAD

**Issue by Wilm0r** [mikenye/docker-planefinder#18]
On an amd64 box I get this, following your instructions:

```
root@oldnuc:~# docker run     --rm     -it     --name pfclient_temp     --entrypoint pfclient     -p 30053:30053     ghcr.io/sdr-enthusiasts/docker-planefinder:latest
standard_init_linux.go:219: exec user process caused: exec format error
```

From what I can tell this error means one's trying to run a binary on the wrong architecture. In `Dockerfile` I see qemu's being used to address this, but this may not actually be necessary? I see native amd64 and even i386 binaries on https://planefinder.net/coverage/client .

**Comment by mikenye** [comment]
Hi @Wilm0r, this should be resolved.

Please try the following:

```
docker pull ghcr.io/sdr-enthusiasts/docker-planefinder:latest
```

then:

```
docker run \
    --rm \
    -it \
    --name pfclient_temp \
    --entrypoint /firstrun \
    -p 30053:30053 \
    ghcr.io/sdr-enthusiasts/docker-planefinder:latest
```

...noting the new entrypoint.

Thanks.

**Comment by Wilm0r** [comment]
Thank you, yep that's working now!

BTW, still curious why it uses the ARM binary through qemu despite there being a native amd64 binary available. It works and it's not a very busy binary so it doesn't matter much, but it still seems less efficient?

**Comment by mikenye** [comment]
@Wilm0r you are right, it is less efficient. The problem is that the plane finder team don’t release different architectures at the same time. The ARM binaries are always ahead by a few versions. This makes it difficult for me to maintain and troubleshoot. It makes it easier for everyone if I run the same binary everywhere, and the same version. 

Ideally, it’d be good if they would follow in the steps of FlightAware and Radarbox and open source their feeder. Then I can compile it for each architecture and we all win. :-)
